"""Failure-learning — turn repeated mistakes into durable agent guidance.

Agents repeat the same failures (wrong command flag, bad path assumption,
flaky retry) across sessions. This module records outcomes offline, finds the
failures that recur, and writes them as corrections into the agent's own
instructions file (``CLAUDE.md`` / ``AGENTS.md``) inside a managed block — so
the next run starts already knowing.

Flow:

    log = FailureLog("reduction-failures.jsonl")
    log.record(context="run pytest", action="pytest -k foo", outcome="fail",
               error="no tests ran: bad -k expression")
    ...
    corrections = log.derive_corrections(min_occurrences=2)
    write_corrections("CLAUDE.md", corrections)
"""

from __future__ import annotations

import json
import threading
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path

BEGIN_MARKER = "<!-- reduction:learned:begin -->"
END_MARKER = "<!-- reduction:learned:end -->"


@dataclass
class FailureRecord:
    context: str
    action: str
    outcome: str  # "fail" | "success"
    error: str = ""


@dataclass
class Correction:
    pattern: str
    occurrences: int
    guidance: str


class FailureLog:
    """Append-only JSONL log of agent outcomes."""

    def __init__(self, path: str | Path = "reduction-failures.jsonl") -> None:
        self.path = Path(path)
        self._lock = threading.Lock()

    def record(self, *, context: str, action: str, outcome: str, error: str = "") -> None:
        rec = FailureRecord(context=context, action=action, outcome=outcome, error=error)
        with self._lock, self.path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(asdict(rec)) + "\n")

    def records(self) -> list[FailureRecord]:
        if not self.path.exists():
            return []
        out: list[FailureRecord] = []
        for line in self.path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                out.append(FailureRecord(**json.loads(line)))
        return out

    def derive_corrections(self, *, min_occurrences: int = 2) -> list[Correction]:
        """Group recurring failures (by action + error) into corrections."""
        failures = [r for r in self.records() if r.outcome == "fail"]
        counter: Counter[tuple[str, str]] = Counter()
        for r in failures:
            counter[(r.action.strip(), r.error.strip())] += 1

        corrections: list[Correction] = []
        for (action, error), count in counter.most_common():
            if count < min_occurrences:
                continue
            guidance = f"When about to `{action}`: previously failed - {error}. Avoid or fix first."
            corrections.append(Correction(pattern=action, occurrences=count, guidance=guidance))
        return corrections


def render_corrections(corrections: list[Correction]) -> str:
    if not corrections:
        return ""
    lines = [BEGIN_MARKER, "## Learned corrections (auto-generated by reduction)", ""]
    for c in corrections:
        lines.append(f"- {c.guidance} _(seen {c.occurrences}x)_")
    lines.append(END_MARKER)
    return "\n".join(lines)


def write_corrections(path: str | Path, corrections: list[Correction]) -> bool:
    """Insert/replace the managed corrections block in ``path``. Returns True if written."""
    block = render_corrections(corrections)
    if not block:
        return False
    target = Path(path)
    existing = target.read_text(encoding="utf-8") if target.exists() else ""

    if BEGIN_MARKER in existing and END_MARKER in existing:
        pre = existing.split(BEGIN_MARKER)[0].rstrip()
        post = existing.split(END_MARKER, 1)[1].lstrip()
        new = f"{pre}\n\n{block}\n\n{post}".strip() + "\n"
    else:
        new = (existing.rstrip() + "\n\n" + block + "\n").lstrip()
    target.write_text(new, encoding="utf-8")
    return True
