"""Failure-learning — turn repeated mistakes into durable agent guidance.

Agents repeat the same failures (wrong command flag, bad path assumption,
flaky retry) across sessions. This module records outcomes offline, finds the
failures that recur, and writes them as corrections into the agent's own
instructions file (``CLAUDE.md`` / ``AGENTS.md``) inside a managed block — so
the next run starts already knowing.

Flow:

    log = FailureLog("reduction-failures.jsonl")
    log.record(context="run pytest", action="pytest -k foo", outcome="fail",
               error="no tests ran: bad -k expression")
    ...
    corrections = log.derive_corrections(min_occurrences=2)
    write_corrections("CLAUDE.md", corrections)
"""

from __future__ import annotations

import json
import re
import threading
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path

# Strip volatile bits so variant wordings of the same failure cluster together.
_NUM = re.compile(r"\d+")
_HEX = re.compile(r"\b0x[0-9a-fA-F]+\b|\b[0-9a-fA-F]{8,}\b")
_PATH = re.compile(r"(?:[A-Za-z]:)?(?:[\\/][\w.\-]+){2,}")
_QUOTED = re.compile(r"['\"`][^'\"`]*['\"`]")
_WS = re.compile(r"\s+")


def normalize_error(text: str) -> str:
    """Collapse an error string to a signature that ignores volatile specifics."""
    s = text.lower()
    s = _PATH.sub("<path>", s)
    s = _HEX.sub("<hex>", s)
    s = _QUOTED.sub("<str>", s)
    s = _NUM.sub("<n>", s)
    return _WS.sub(" ", s).strip()


BEGIN_MARKER = "<!-- reduction:learned:begin -->"
END_MARKER = "<!-- reduction:learned:end -->"


@dataclass
class FailureRecord:
    context: str
    action: str
    outcome: str  # "fail" | "success"
    error: str = ""


@dataclass
class Correction:
    pattern: str
    occurrences: int
    guidance: str


class FailureLog:
    """Append-only JSONL log of agent outcomes."""

    def __init__(self, path: str | Path = "reduction-failures.jsonl") -> None:
        self.path = Path(path)
        self._lock = threading.Lock()

    def record(self, *, context: str, action: str, outcome: str, error: str = "") -> None:
        rec = FailureRecord(context=context, action=action, outcome=outcome, error=error)
        with self._lock, self.path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(asdict(rec)) + "\n")

    def records(self) -> list[FailureRecord]:
        if not self.path.exists():
            return []
        out: list[FailureRecord] = []
        for line in self.path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                out.append(FailureRecord(**json.loads(line)))
        return out

    def derive_corrections(self, *, min_occurrences: int = 2) -> list[Correction]:
        """Group recurring failures into corrections.

        Grouping is by action + *normalized* error signature, so variant
        wordings of the same failure ("no tests ran" vs "0 tests collected in
        2.3s") still cluster. A representative raw error is kept for the message.
        """
        failures = [r for r in self.records() if r.outcome == "fail"]
        counter: Counter[tuple[str, str]] = Counter()
        examples: dict[tuple[str, str], str] = {}
        for r in failures:
            key = (r.action.strip(), normalize_error(r.error))
            counter[key] += 1
            examples.setdefault(key, r.error.strip())

        corrections: list[Correction] = []
        for (action, _sig), count in counter.most_common():
            if count < min_occurrences:
                continue
            error = examples[(action, _sig)]
            guidance = f"When about to `{action}`: previously failed - {error}. Avoid or fix first."
            corrections.append(Correction(pattern=action, occurrences=count, guidance=guidance))
        return corrections


def render_corrections(corrections: list[Correction]) -> str:
    if not corrections:
        return ""
    lines = [BEGIN_MARKER, "## Learned corrections (auto-generated by reduction)", ""]
    for c in corrections:
        lines.append(f"- {c.guidance} _(seen {c.occurrences}x)_")
    lines.append(END_MARKER)
    return "\n".join(lines)


def write_corrections(path: str | Path, corrections: list[Correction]) -> bool:
    """Insert/replace the managed corrections block in ``path``. Returns True if written."""
    block = render_corrections(corrections)
    if not block:
        return False
    target = Path(path)
    existing = target.read_text(encoding="utf-8") if target.exists() else ""

    if BEGIN_MARKER in existing and END_MARKER in existing:
        pre = existing.split(BEGIN_MARKER)[0].rstrip()
        post = existing.split(END_MARKER, 1)[1].lstrip()
        new = f"{pre}\n\n{block}\n\n{post}".strip() + "\n"
    else:
        new = (existing.rstrip() + "\n\n" + block + "\n").lstrip()
    target.write_text(new, encoding="utf-8")
    return True
